/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace RentalAgreementNFT {
  export type TermsStruct = {
    landlord: AddressLike;
    tenant: AddressLike;
    start: BigNumberish;
    end: BigNumberish;
    rentPerPeriod: BigNumberish;
    termsHash: BytesLike;
  };

  export type TermsStructOutput = [
    landlord: string,
    tenant: string,
    start: bigint,
    end: bigint,
    rentPerPeriod: bigint,
    termsHash: string
  ] & {
    landlord: string;
    tenant: string;
    start: bigint;
    end: bigint;
    rentPerPeriod: bigint;
    termsHash: string;
  };
}

export interface DepositStakingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "asset"
      | "deposit"
      | "escrow"
      | "landlordClaim"
      | "nft"
      | "owner"
      | "renounceOwnership"
      | "tenantWithdrawAfterEnd"
      | "termsWithBalance"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClaimedByLandlord"
      | "Deposited"
      | "OwnershipTransferred"
      | "WithdrawnByTenant"
  ): EventFragment;

  encodeFunctionData(functionFragment: "asset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "landlordClaim",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "nft", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tenantWithdrawAfterEnd",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "termsWithBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "asset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "landlordClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nft", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tenantWithdrawAfterEnd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "termsWithBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ClaimedByLandlordEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    landlord: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    landlord: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    landlord: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    from: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [tokenId: bigint, from: string, amount: bigint];
  export interface OutputObject {
    tokenId: bigint;
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnByTenantEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    tenant: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [tokenId: bigint, tenant: string, amount: bigint];
  export interface OutputObject {
    tokenId: bigint;
    tenant: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DepositStaking extends BaseContract {
  connect(runner?: ContractRunner | null): DepositStaking;
  waitForDeployment(): Promise<this>;

  interface: DepositStakingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  asset: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  escrow: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  landlordClaim: TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  nft: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  tenantWithdrawAfterEnd: TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  termsWithBalance: TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [RentalAgreementNFT.TermsStructOutput, bigint] & {
        terms: RentalAgreementNFT.TermsStructOutput;
        balance: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "asset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "landlordClaim"
  ): TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nft"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tenantWithdrawAfterEnd"
  ): TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "termsWithBalance"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [RentalAgreementNFT.TermsStructOutput, bigint] & {
        terms: RentalAgreementNFT.TermsStructOutput;
        balance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ClaimedByLandlord"
  ): TypedContractEvent<
    ClaimedByLandlordEvent.InputTuple,
    ClaimedByLandlordEvent.OutputTuple,
    ClaimedByLandlordEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawnByTenant"
  ): TypedContractEvent<
    WithdrawnByTenantEvent.InputTuple,
    WithdrawnByTenantEvent.OutputTuple,
    WithdrawnByTenantEvent.OutputObject
  >;

  filters: {
    "ClaimedByLandlord(uint256,address,uint256,string)": TypedContractEvent<
      ClaimedByLandlordEvent.InputTuple,
      ClaimedByLandlordEvent.OutputTuple,
      ClaimedByLandlordEvent.OutputObject
    >;
    ClaimedByLandlord: TypedContractEvent<
      ClaimedByLandlordEvent.InputTuple,
      ClaimedByLandlordEvent.OutputTuple,
      ClaimedByLandlordEvent.OutputObject
    >;

    "Deposited(uint256,address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WithdrawnByTenant(uint256,address,uint256)": TypedContractEvent<
      WithdrawnByTenantEvent.InputTuple,
      WithdrawnByTenantEvent.OutputTuple,
      WithdrawnByTenantEvent.OutputObject
    >;
    WithdrawnByTenant: TypedContractEvent<
      WithdrawnByTenantEvent.InputTuple,
      WithdrawnByTenantEvent.OutputTuple,
      WithdrawnByTenantEvent.OutputObject
    >;
  };
}
