/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SignatureVerifier {
  export type VoucherStruct = {
    payer: AddressLike;
    payee: AddressLike;
    agreementId: BigNumberish;
    amount: BigNumberish;
    nonce: BigNumberish;
    expiry: BigNumberish;
  };

  export type VoucherStructOutput = [
    payer: string,
    payee: string,
    agreementId: bigint,
    amount: bigint,
    nonce: bigint,
    expiry: bigint
  ] & {
    payer: string;
    payee: string;
    agreementId: bigint;
    amount: bigint;
    nonce: bigint;
    expiry: bigint;
  };
}

export interface RentChannelInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "channels"
      | "close"
      | "depositMore"
      | "nft"
      | "open"
      | "timeout"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Closed" | "Deposited" | "Opened" | "TimeoutClosed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "channels",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "close",
    values: [SignatureVerifier.VoucherStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositMore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nft", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "open",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "timeout",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "channels", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "close", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositMore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nft", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "open", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "timeout", data: BytesLike): Result;
}

export namespace ClosedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    paidToPayee: BigNumberish
  ];
  export type OutputTuple = [agreementId: bigint, paidToPayee: bigint];
  export interface OutputObject {
    agreementId: bigint;
    paidToPayee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [agreementId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [agreementId: bigint, amount: bigint];
  export interface OutputObject {
    agreementId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OpenedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    payer: AddressLike,
    payee: AddressLike,
    deposit: BigNumberish,
    timeoutAt: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: bigint,
    payer: string,
    payee: string,
    deposit: bigint,
    timeoutAt: bigint
  ];
  export interface OutputObject {
    agreementId: bigint;
    payer: string;
    payee: string;
    deposit: bigint;
    timeoutAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimeoutClosedEvent {
  export type InputTuple = [agreementId: BigNumberish, refunded: BigNumberish];
  export type OutputTuple = [agreementId: bigint, refunded: bigint];
  export interface OutputObject {
    agreementId: bigint;
    refunded: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RentChannel extends BaseContract {
  connect(runner?: ContractRunner | null): RentChannel;
  waitForDeployment(): Promise<this>;

  interface: RentChannelInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  channels: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        payer: string;
        payee: string;
        deposit: bigint;
        claimed: bigint;
        nonce: bigint;
        timeoutAt: bigint;
        open: boolean;
      }
    ],
    "view"
  >;

  close: TypedContractMethod<
    [v: SignatureVerifier.VoucherStruct, sig: BytesLike],
    [void],
    "nonpayable"
  >;

  depositMore: TypedContractMethod<
    [agreementId: BigNumberish],
    [void],
    "payable"
  >;

  nft: TypedContractMethod<[], [string], "view">;

  open: TypedContractMethod<
    [agreementId: BigNumberish, timeoutSeconds: BigNumberish],
    [void],
    "payable"
  >;

  timeout: TypedContractMethod<
    [agreementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "channels"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        payer: string;
        payee: string;
        deposit: bigint;
        claimed: bigint;
        nonce: bigint;
        timeoutAt: bigint;
        open: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "close"
  ): TypedContractMethod<
    [v: SignatureVerifier.VoucherStruct, sig: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositMore"
  ): TypedContractMethod<[agreementId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "nft"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "open"
  ): TypedContractMethod<
    [agreementId: BigNumberish, timeoutSeconds: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "timeout"
  ): TypedContractMethod<[agreementId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Closed"
  ): TypedContractEvent<
    ClosedEvent.InputTuple,
    ClosedEvent.OutputTuple,
    ClosedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Opened"
  ): TypedContractEvent<
    OpenedEvent.InputTuple,
    OpenedEvent.OutputTuple,
    OpenedEvent.OutputObject
  >;
  getEvent(
    key: "TimeoutClosed"
  ): TypedContractEvent<
    TimeoutClosedEvent.InputTuple,
    TimeoutClosedEvent.OutputTuple,
    TimeoutClosedEvent.OutputObject
  >;

  filters: {
    "Closed(uint256,uint256)": TypedContractEvent<
      ClosedEvent.InputTuple,
      ClosedEvent.OutputTuple,
      ClosedEvent.OutputObject
    >;
    Closed: TypedContractEvent<
      ClosedEvent.InputTuple,
      ClosedEvent.OutputTuple,
      ClosedEvent.OutputObject
    >;

    "Deposited(uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Opened(uint256,address,address,uint256,uint64)": TypedContractEvent<
      OpenedEvent.InputTuple,
      OpenedEvent.OutputTuple,
      OpenedEvent.OutputObject
    >;
    Opened: TypedContractEvent<
      OpenedEvent.InputTuple,
      OpenedEvent.OutputTuple,
      OpenedEvent.OutputObject
    >;

    "TimeoutClosed(uint256,uint256)": TypedContractEvent<
      TimeoutClosedEvent.InputTuple,
      TimeoutClosedEvent.OutputTuple,
      TimeoutClosedEvent.OutputObject
    >;
    TimeoutClosed: TypedContractEvent<
      TimeoutClosedEvent.InputTuple,
      TimeoutClosedEvent.OutputTuple,
      TimeoutClosedEvent.OutputObject
    >;
  };
}
